CREATE DATABASE IF NOT EXISTS bWAPP
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'bwapp_user'@'%' IDENTIFIED BY 'bwapp_pass';
GRANT ALL PRIVILEGES ON bWAPP.* TO 'bwapp_user'@'%';
FLUSH PRIVILEGES;

